version: '2.4'
services:
  web:
    restart: unless-stopped
    container_name: web
    build:
      context: ./web
    volumes:
      - ./web/:/home/global-cell/web
      - ./cert/:/home/global-cell
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn -c conf/gunicorn_conf.py core.wsgi:application"
    expose:
      - '8000'
    depends_on:
      - postgres
      - redis
    env_file:
      - env.example
  nginx:
    restart: unless-stopped
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cert/:/home/global-cell
      - ./web/static/:/home/global-cell/web/static
      - ./web/media/:/home/global-cell/web/media
      - ./web/staticfiles/:/home/global-cell/web/staticfiles
    depends_on:
      - web
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./pg/:/var/lib/postgresql/data
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis
    ports:
      - '6379:6379'